// <auto-generated />
using System;
using CuaHang.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHang.Models.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240114155510_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHang.Models.Entities.Cart_item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cartID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("cartID");

                    b.HasIndex("productId");

                    b.ToTable("Cart_item");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Carts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("nguoiDungId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.EmailValidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXacNhan")
                        .HasColumnType("bit");

                    b.Property<int?>("MaXacNhan")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("XacNhanEmail");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId")
                        .IsUnique()
                        .HasFilter("[TaiKhoanId] IS NOT NULL");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("actual_price")
                        .HasColumnType("float");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("order_statusID")
                        .HasColumnType("int");

                    b.Property<double?>("original_price")
                        .HasColumnType("float");

                    b.Property<int>("paymentID")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("nguoiDungId");

                    b.HasIndex("order_statusID");

                    b.HasIndex("paymentID");

                    b.ToTable("order");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order_detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("orderID")
                        .HasColumnType("int");

                    b.Property<double?>("price_total")
                        .HasColumnType("float");

                    b.Property<int?>("productID")
                        .HasColumnType("int");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("orderID");

                    b.HasIndex("productID");

                    b.ToTable("order_detail");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order_status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("status_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("order_status");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("avartar_image_product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<string>("name_product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number_of_views")
                        .HasColumnType("int");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<int>("product_typeID")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("product_typeID");

                    b.ToTable("product");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product_review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("content_rated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content_seen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("point_evaluation")
                        .HasColumnType("int");

                    b.Property<int>("productID")
                        .HasColumnType("int");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("nguoiDungId");

                    b.HasIndex("productID");

                    b.ToTable("product_review");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product_type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("image_type_product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_product_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("product_type");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiredTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("accountID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("accountID");

                    b.ToTable("Refresh_token");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Cart_item", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.Carts", "cart")
                        .WithMany("cart_Items")
                        .HasForeignKey("cartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHang.Models.Entities.Product", "product")
                        .WithMany("cart_Items")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Carts", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.NguoiDung", "nguoiDung")
                        .WithMany("carts")
                        .HasForeignKey("nguoiDungId");

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.EmailValidate", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("emailValidates")
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.NguoiDung", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("nguoiDung")
                        .HasForeignKey("CuaHang.Models.Entities.NguoiDung", "TaiKhoanId");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.NguoiDung", "nguoiDung")
                        .WithMany("orders")
                        .HasForeignKey("nguoiDungId");

                    b.HasOne("CuaHang.Models.Entities.Order_status", "order_Status")
                        .WithMany("orders")
                        .HasForeignKey("order_statusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHang.Models.Entities.Payment", "Payment")
                        .WithMany("orders")
                        .HasForeignKey("paymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("nguoiDung");

                    b.Navigation("order_Status");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order_detail", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.Order", "order")
                        .WithMany("order_Details")
                        .HasForeignKey("orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHang.Models.Entities.Product", "product")
                        .WithMany("order_Details")
                        .HasForeignKey("productID");

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.Product_type", "product")
                        .WithMany("products")
                        .HasForeignKey("product_typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product_review", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.NguoiDung", "nguoiDung")
                        .WithMany("product_review")
                        .HasForeignKey("nguoiDungId");

                    b.HasOne("CuaHang.Models.Entities.Product", "product")
                        .WithMany("reviews")
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoiDung");

                    b.Navigation("product");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.TaiKhoan", "account")
                        .WithMany("refreshTokens")
                        .HasForeignKey("accountID");

                    b.Navigation("account");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("CuaHang.Models.Entities.Role", "Role")
                        .WithMany("TaiKhoan")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Carts", b =>
                {
                    b.Navigation("cart_Items");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("orders");

                    b.Navigation("product_review");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order", b =>
                {
                    b.Navigation("order_Details");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Order_status", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Payment", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product", b =>
                {
                    b.Navigation("cart_Items");

                    b.Navigation("order_Details");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Product_type", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.Role", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CuaHang.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("emailValidates");

                    b.Navigation("nguoiDung")
                        .IsRequired();

                    b.Navigation("refreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
